### ISSUE TITLE
Защита от переполюсовки

### ISSUE THREAD

**Issue by glitchcore** [microrack/VCO#10]
Поставить защиту на линию +9В
![image](https://user-images.githubusercontent.com/12886640/99941969-f3d74500-2d7f-11eb-8896-1c179d7fce78.png)

Можно взять IRLML5203.

Линию -9В защищать не нужно.

**Comment by Krasnov-Max** [comment]
Finished

**Comment by glitchcore** [comment]
Диод вверх ногами
