### ISSUE TITLE
Задачи по версии 0.2

### ISSUE THREAD

**Issue by glitchcore** [microrack/VCO#5]
## Исправить схему

* Добавить линейные регуляторы на ±5 В
* Заменить Q1/Q2 на сдвоенный транзистор (подобрать компонент)

Текущее состояние схемы лежит в ветке `vco-a`: готова схема (кроме вышеуказанных замечаний), расставлены компоненты.

## Переделать рэк
Также я уменьшил расстояние между крепежными гребенками, нужно согласовать с рэком (изменить расстояние там).

## Развести

Стараться компоненты распологать с обратной стороны.

**Comment by Krasnov-Max** [comment]
ok. Task finished
