### ISSUE TITLE
Выровнять разъемы и изменить количество PLS

### ISSUE THREAD

**Issue by sntxerror** [microrack/VCO#7]
Расположить крепежные отверстия на одинаковом расстоянии от краев модуля, максимально широко

Расположение PLS для модулей:

cверху
```
. . . .    . . . .
```

снизу
```
 . . .      . . .
. . . .    . . . . 
```

**Comment by Krasnov-Max** [comment]
Диаметр крепежных отверстий? И можно ли увеличить габариты модуля по оси X?

**Comment by Krasnov-Max** [comment]
add moutig hole. Chenge position power connectors. This issue cloased.
