### ISSUE TITLE
Добавить индикаторные светодиоды

### ISSUE THREAD

**Issue by glitchcore** [microrack/VCO#8]
Рядом с выходами saw и sq добавить по одному светодиоду (с внутренней стороны)
![image](https://user-images.githubusercontent.com/12886640/98036270-cd7e5380-1e2a-11eb-85fa-e7df295572b5.png)

Подключить к выходам через 1к
![image](https://user-images.githubusercontent.com/12886640/98036459-22ba6500-1e2b-11eb-85c8-07e34a31bc7a.png)

**Comment by Krasnov-Max** [comment]
Давай придем к тому что стороны на плате называем верхняя (top) где расположены регуляторы, и нижняя (bottom) где расположены разъемы питания.

**Comment by glitchcore** [comment]
Под внутренней стороной я понимал расположение светодиодов относительно контура платы (в центре)
